# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='End',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='Start',
            field=models.IntegerField(),
        ),
    ]
